version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - ALLOWED_HOSTS=http://localhost:5173
      - COOKIE_SECRET=your_secret_key
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

  ws:
    build:
      context: .
      dockerfile: Dockerfile.ws
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: always